export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_AUTH = 'LOGIN_USER_AUTH';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CLOSE_SNACK = 'CLOSE_SNACK';
export const LOGOUT_USER_LOADING = 'LOGOUT_USER_LOADING';
export const LOGOUT_USER_MESSAGE = 'LOGOUT_USER_MESSAGE';
