
export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_ERROR = 'UPDATE_AVATAR_ERROR';
export const FETCH_AVATAR_REQUEST = 'FETCH_AVATAR_REQUEST';
export const FETCH_AVATAR_SUCCESS = 'FETCH_AVATAR_SUCCESS';
export const FETCH_AVATAR_ERROR = 'FETCH_AVATAR_ERROR';