export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR';

export const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE';
export const SET_CURRENT_PAPER = 'SET_CURRENT_PAPER';

